In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

In [12]:
Countries = ['Armenia','Belarus','Kyrgyzstan','Kazakhstan','Russian Federation']

for country in Countries:
    Imports = pd.read_excel(f'C:/TradeGroup/Reports/Eurasia/گزارش/{country}_Imports_Product.xlsx')
    Exports = pd.read_excel(f'C:/TradeGroup/Reports/Eurasia/گزارش/{country}_Exports_Product.xlsx')

    Imports = Imports[['Code','Product label' , 'Y2023']]
    Exports = Exports[['Code','Product label' , 'Y2023']]


    Imports["Rank"] = Imports["Y2023"].rank(ascending=False)
    Exports["Rank"] = Exports["Y2023"].rank(ascending=False)
    

    Imports_First_10 = Imports[Imports['Rank']<11]
    Exports_First_10 = Exports[Exports['Rank']<11]

    Import_Sum_First_10 = pd.DataFrame({'Code':999999,'Product label':"First 10 Sum",'Y2023': Imports_First_10['Y2023'].sum(),'Rank':11},index=[100])
    Export_Sum_First_10 = pd.DataFrame({'Code':999999,'Product label':"First 10 Sum",'Y2023': Exports_First_10['Y2023'].sum(),'Rank':11},index=[100])


    Import_Sum_Other = pd.DataFrame({'Code':9999999,'Product label':"Others Sum",'Y2023': Imports.loc[Imports['Rank']>10,'Y2023'].sum(),'Rank':12},index=[101])
    Export_Sum_Other = pd.DataFrame({'Code':9999999,'Product label':"Others Sum",'Y2023': Exports.loc[Exports['Rank']>10,'Y2023'].sum(),'Rank':12},index=[101])


    Imports_New = pd.concat([Imports_First_10,Import_Sum_First_10])  
    Exports_New = pd.concat([Exports_First_10,Export_Sum_First_10])

    Imports_New_New = pd.concat([Imports_New,Import_Sum_Other])
    Exports_New_New = pd.concat([Exports_New,Export_Sum_Other])

    Imports_New_New.to_excel(f'C:/TradeGroup/Reports/Eurasia/گزارش/{country}_Imports_Product_First10.xlsx')
    Exports_New_New.to_excel(f'C:/TradeGroup/Reports/Eurasia/گزارش/{country}_Exports_Product_First10.xlsx')

In [11]:
Exports_New_New

,Code,Product label,Y2023,Rank
0,270900,Petroleum oils and oils obtained from bitumino...,120510995.0,1.0
1,271019,"Medium oils and preparations, of petroleum or ...",38027072.0,2.0
2,270112,"Bituminous coal, whether or not pulverised, no...",21097755.0,3.0
3,999999,Commodities not elsewhere specified,20550426.0,4.0
4,271111,"Natural gas, liquefied",19771499.0,5.0
5,271121,Natural gas in gaseous state,18617815.0,6.0
6,271012,"Light oils and preparations, of petroleum or b...",11380888.0,7.0
7,710812,"Gold, incl. gold plated with platinum, unwroug...",10858085.0,8.0
8,100199,"Wheat and meslin (excl. seed for sowing, and d...",6184545.0,9.0
9,760110,"Aluminium, not alloyed, unwrought",5579045.0,10.0
100,999999,First 10 Sum,272578125.0,11.0
101,9999999,Others Sum,135273861.0,12.0