In [54]:
import pandas as pd
import numpy as np
import os

In [55]:
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

In [56]:
Exchange = pd.read_excel(f'{my_wd}/Reports/Arz_1402-14031.xlsx')

In [57]:
Ex_Col_names= ['Samaneh','Bank','Sabt_Sefaresh','Arz_Value','Arz_Type','Tcode','Tdesc',
               'Motaghazi','National_ID','National_Code','Dollars','MDollars','Euroes',
               'MEuroes',' Takhsis_Type','Full_Date','Bakhshanmeh','ForWhat']
Exchange.columns = Ex_Col_names

Exchange['Tcode'] = Exchange['Tcode'].fillna(0).astype('int')

In [58]:
Exchange['HS6']= Exchange['Tcode']//100
Exchange['HS5']= Exchange['Tcode']//1000

In [73]:
Exchange

,Samaneh,Bank,Sabt_Sefaresh,Arz_Value,Arz_Type,Tcode,Tdesc,Motaghazi,National_ID,National_Code,Dollars,MDollars,Euroes,MEuroes,Takhsis_Type,Full_Date,Bakhshanmeh,ForWhat,HS6,HS5
0,تامین,بانک شهر,94967166.0,1067644.94,یورو,10059010,دانه ذرت دامی، فاقد بسته‌بندی تجاری، غیر تراریخته,صبا پيشرو کالا,383752418.0,1.400482e+10,1148946.10,1.148946,1067644.94,1.067645,ترجیحی,1402/01/05,291890,NaN,100590,10059
1,تامین,بانک شهر,94967166.0,5338.22,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,صبا پيشرو کالا,383752418.0,1.400482e+10,5744.73,0.005745,5338.22,0.005338,ترجیحی,1402/01/05,291890,NaN,994602,99460
2,تامین,بانک پاسارگاد,95948166.0,13538122.61,یورو,10059010,دانه ذرت دامی، فاقد بسته‌بندی تجاری، تراریخته,آوا تجارت صبا,839534205.0,1.032051e+10,14569050.65,14.569051,13538122.61,13.538123,ترجیحی,1402/01/05,291890,NaN,100590,10059
3,تامین,بانک پاسارگاد,95948166.0,67690.61,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,آوا تجارت صبا,839534205.0,1.032051e+10,72845.25,0.072845,67690.61,0.067691,ترجیحی,1402/01/05,291890,NaN,994602,99460
4,تامین,بانک کشاورزی,85375336.0,39750.00,یورو,30049092,سل سپت قرص خوراکی 500 mg,يارا طب خاورميانه,72381582.0,1.010324e+10,42776.96,0.042777,39750.00,0.039750,ترجیحی,1402/01/05,198114;291890,NaN,300490,30049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639753,نیما,بانک تجارت,29334882.0,401.65,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,رويان دارو,NaN,1.048010e+10,427.48,0.000427,401.65,0.000402,تالاردوم,1403/01/30,NaN,NaN,994602,99460
639754,نیما,بانک تجارت,29334769.0,567.06,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,رويان دارو,NaN,1.048010e+10,603.53,0.000604,567.06,0.000567,تالاردوم,1403/01/30,NaN,NaN,994602,99460
639755,نیما,بانک تجارت,29494603.0,4187.68,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,ماشين سازي تاشا,NaN,1.086067e+10,4456.99,0.004457,4187.68,0.004188,تالاردوم,1403/01/30,NaN,NaN,994602,99460
639756,نیما,بانک تجارت,29334769.0,50.00,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,رويان دارو,NaN,1.048010e+10,53.22,0.000053,50.00,0.000050,تالاردوم,1403/01/30,NaN,NaN,994602,99460
639757,نیما,بانک تجارت,26664683.0,64.00,یورو,99460200,حق الزحمه تبديل و کارمزد انتقال ارز,پويا مبدل کيميا,NaN,1.053045e+10,68.12,0.000068,64.00,0.000064,تالاردوم,1403/01/30,NaN,NaN,994602,99460

In [59]:
HSs_Desc=pd.read_excel(f"C:/TradeGroup/Data/Dashboard/HSs_complete_Final.xlsx")

In [68]:
Exchange_Merged = Exchange.merge(HSs_Desc,on=['HS6','HS5'],how='left')
Exchange_Merged_NAs = Exchange_Merged[Exchange_Merged['HS4'].isnull()]
Exchange_Merged_NonNAs = Exchange_Merged[~Exchange_Merged['HS4'].isnull()]

Exchange_Merged_NAs_tobemerged = Exchange[Exchange['Tcode'].isin(Exchange_Merged_NAs['Tcode'])]

In [76]:
HSs_Desc_WOHS6 =HSs_Desc.drop(['HS6'],axis=1)
HSs_Desc_WOHS6 = HSs_Desc_WOHS6.drop_duplicates(subset='HS5', keep='first')

Exchange_Merged_NAs_tobemerged_merge = Exchange_Merged_NAs_tobemerged.merge(HSs_Desc_WOHS6,on='HS5',how='left')



Exchange_Merged_NAs_tobemerged_merge

,Samaneh,Bank,Sabt_Sefaresh,Arz_Value,Arz_Type,Tcode,Tdesc,Motaghazi,National_ID,National_Code,...,HS6_E,HS6_F,HS4,HS2,HS4_E,HS4_F,Harvard_F,HS2_F,Harvard_E,HS2_E
0,تامین,بانک پارسيان,73672297.0,1243003.00,یورو,90278950,blood glucose test strips in uncut sheets نوار...,خدمات مخابراتي ارگ جديد,6.273126e+07,1.010233e+10,...,"Equipment for physical or chemical analysis, nes",تجهیزات برای تجزیه و تحلیل فیزیکی یا شیمیایی،...,9027.0,90.0,Instruments for physical or chemical analysis,ابزار برای تجزیه و تحلیل فیزیکی یا شیمیایی,ماشین‌آلات,آلات و دستگاه‌های اپتیک، عکاسی، سینماتوگرافی، ...,Machinery,Apparatuses
1,تامین,بانک ملت,NaN,15000.00,یورو,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,تامین,بانک پارسيان,93606660.0,49680.00,یورو,38249990,عامل چسباننده,گروه صنعتي بارز,8.586824e+08,1.010098e+10,...,"Products, Prepara.,Residual Prdcts of Chemica...",محصولات، آماده سازی، محصولات باقیمانده از صنا...,3824.0,38.0,Prepared binders for foundry moulds,چسباننده‌های آماده برای قالب‌ها,محصولات شیمیایی,محصولات شیمیایی متفرقه,Chemicals,Miscellaneous chemical products
3,تامین,بانک سامان,11876831.0,687585.00,یورو,38249990,Dental Zirconia Block HT 98*10 بلوك كدكم 1,صدرا اقليم آرمان,7.685184e+07,1.400511e+10,...,"Products, Prepara.,Residual Prdcts of Chemica...",محصولات، آماده سازی، محصولات باقیمانده از صنا...,3824.0,38.0,Prepared binders for foundry moulds,چسباننده‌های آماده برای قالب‌ها,محصولات شیمیایی,محصولات شیمیایی متفرقه,Chemicals,Miscellaneous chemical products
4,تامین,بانک پارسيان,14408188.0,670800.00,یورو,38123910,آنتی اکسیدان 6 پی پی دی,لاستيک بارز کردستان,5.589848e+09,1.032017e+10,...,Anti-oxidisers and stabilizers for rubber or ...,آنتی اکسیدان‌ها و تثبیت‌کننده‌ها برای لاستیک ...,3812.0,38.0,Stabilizers for rubber or plastic,تثبیت‌کننده‌های لاستیکی یا پلاستیکی,محصولات شیمیایی,محصولات شیمیایی متفرقه,Chemicals,Miscellaneous chemical products
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68728,نیما,بانک تجارت,27219680.0,78214.36,یورو,85414100,ديود، LED، نصب SMD، سازنده BRIGHTEK OPTOELECTR...,صنايع توليدي کروز,NaN,1.010108e+10,...,Photosensitive/photovoltaic/LED semiconductor...,دستگاه‌های نیمه‌هادی حساس به نور/فتوولتائیک/LED,8541.0,85.0,Semiconductor devices,دستگاه‌های نیمه‌هادی,وسایل الکترونیکی,ماشین‌آلات و تجهیزات الکتریکی,Electronics,Electrical machinery and equipment
68729,نیما,بانک تجارت,28390645.0,23871.17,دلار آمریکا,39076110,گرانول پلي اتيلن ترفتالات، كاربرد نساجي، گريد ...,توليدي ايران نو بافت,NaN,1.026023e+10,...,"Polyethylene terephthalate, in primary forms",پلی اتیلن ترفتالات، در اشکال اولیه,3907.0,39.0,Polyacetals,پلی استال ها,محصولات شیمیایی,پلاستیک‌ها,Chemicals,Plastics
68730,نیما,بانک تجارت,25603740.0,1905560.00,درهم امارات,39076110,چیپس پلی استر,قيام نخ,NaN,1.010327e+10,...,"Polyethylene terephthalate, in primary forms",پلی اتیلن ترفتالات، در اشکال اولیه,3907.0,39.0,Polyacetals,پلی استال ها,محصولات شیمیایی,پلاستیک‌ها,Chemicals,Plastics
68731,نیما,بانک تجارت,22383207.0,148005.81,دلار آمریکا,85171390,تلفن همراه، دو سيم كارت، حافظه 128 GB، SAMSUNG...,رايکا تجارت آريا همراه,NaN,1.400975e+10,...,Telephone sets,دستگاه‌های تلفن,8517.0,85.0,Telephones,تلفن‌ها,وسایل الکترونیکی,ماشین‌آلات و تجهیزات الکتریکی,Electronics,Electrical machinery and equipment
68732,نیما,بانک صادرات ایران,28884029.0,565974.15,درهم امارات,44071190,الوار، نوع معمولي، مستطيلي، از چوب نراد، سازند...,بين المللي سپند مهر خالق خزر,NaN,1.400934e+10,...,"Lumber, coniferous (softwood) thickness < 6 mm",الوار، مخروطی (چوب نرم) ضخامت < 6 میلی متر,4407.0,44.0,Wood sawn lengthwise,چوب اره‌شده از طول,کشاورزی,چوب,Agriculture,Wood

In [77]:
Exchange_concated_final = pd.concat([Exchange_Merged_NonNAs,Exchange_Merged_NAs_tobemerged_merge])



columns_to_replace = Exchange_concated_final.iloc[:, 10:]

Exchange_concated_final.iloc[:, 10:] = columns_to_replace.fillna(0)

In [78]:
Exchange_concated_final_HS2_Zeros = Exchange_concated_final[Exchange_concated_final['HS2']==0]
Exchange_concated_final_HS2_Zeros

,Samaneh,Bank,Sabt_Sefaresh,Arz_Value,Arz_Type,Tcode,Tdesc,Motaghazi,National_ID,National_Code,...,HS6_E,HS6_F,HS4,HS2,HS4_E,HS4_F,Harvard_F,HS2_F,Harvard_E,HS2_E
1,تامین,بانک ملت,NaN,15000.00,یورو,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
6,تامین,بانک ملت,NaN,5000.00,یورو,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
10,تامین,بانک ملت,NaN,1500.00,دلار آمریکا,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
11,تامین,بانک ملت,NaN,4300.00,دلار آمریکا,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
12,تامین,بانک ملت,NaN,15500.00,دلار آمریکا,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,تامین,بانک ملت,NaN,10000.00,یورو,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
494,تامین,بانک ملت,NaN,2820.00,یورو,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
495,تامین,بانک ملت,NaN,27600.00,یورو,0,NaN,NaN,NaN,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0
12793,تامین از صادرات,NaN,87654321.0,0.01,دلار امریکا,0,تستی,تستي ...,1.234568e+09,1.234568e+09,...,0,0,0.0,0.0,0,0,0,0,0,0
62754,نیما,بانک صنعت ‌و ‌معدن,31622468.0,22000.00,یورو,11111111,نا مشخص,الياف گستريزد,1.111111e+09,NaN,...,0,0,0.0,0.0,0,0,0,0,0,0

In [79]:
Exchange_concated_final.to_excel(f"C:/TradeGroup/Reports/ArzTakhsisi_Alpha.xlsx", index=False)

We do not need this part anymore

In [17]:
Exchange_Merged_NAs_tobemerged_merge_NAs = Exchange_Merged_NAs_tobemerged_merge[Exchange_Merged_NAs_tobemerged_merge['HS2'].isnull()]
Exchange_Merged_NAs_tobemerged_merge_NAs.to_excel(f"C:/TradeGroup/Reports/Arz_1402_14031nas.xlsx",index=False)

-------------------------------------

In [80]:
Exchange_concated_final['Year']=Exchange_concated_final['Full_Date'].str.slice(0,4).astype('int')
Exchange_concated_final['Month']=Exchange_concated_final['Full_Date'].str.slice(5,7).astype('int')
Exchange_concated_final['Day']=Exchange_concated_final['Full_Date'].str.slice(9,10).astype('int')

In [81]:
Exchange_concated_final.loc[(Exchange_concated_final['HS6']==999999) |
                                                   ((Exchange_concated_final['HS6']>0)&(Exchange_concated_final['HS6']<990000)),'HS_Type']="Good"


Exchange_concated_final.loc[((Exchange_concated_final['HS6']<999999)&(Exchange_concated_final['HS6']>990000)),'HS_Type']="Service"

Exchange_concated_final.loc[(Exchange_concated_final['HS6']==0),'HS_Type']="Other"

Exchange_new = Exchange_concated_final

In [103]:
Takhsis_Type=Exchange_concated_final.groupby(['Year','Month',' Takhsis_Type']).agg(
    MDollars = ('MDollars','sum')
).reset_index()



Month=Exchange_concated_final.groupby(['Year','Month']).agg(
    MDollars = ('MDollars','sum')
).reset_index()

HS_Type=Exchange_concated_final.groupby('HS_Type').agg(
    MDollars = ('MDollars','sum')
).reset_index()


HS_Type_Month=Exchange_concated_final.groupby(['Year','Month','HS_Type']).agg(

    MDollars = ('MDollars','sum')
).reset_index()



HS2_Total=Exchange_concated_final.groupby(['HS_Type','HS2']).agg(
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()

HS2_Year=Exchange_concated_final.groupby(['Year','HS_Type','HS2',]).agg(
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()



HS2_Month=Exchange_concated_final.groupby(['Year','Month','HS_Type','HS2']).agg(
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()






HS4_Total=Exchange_concated_final.groupby(['HS_Type','HS4']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()

HS4_Year=Exchange_concated_final.groupby(['Year','HS_Type','HS4']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()



HS4_Month=Exchange_concated_final.groupby(['Year','Month','HS_Type','HS4']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()






HS6_Total=Exchange_concated_final.groupby(['HS_Type','HS6']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()

HS6_Year=Exchange_concated_final.groupby(['Year','HS_Type','HS6']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()



HS6_Month=Exchange_concated_final.groupby(['Year','Month','HS_Type','HS6']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    MDollars = ('MDollars','sum')
).reset_index()





HS8_Total=Exchange_concated_final.groupby(['HS_Type','Tcode']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()

HS8_Year=Exchange_concated_final.groupby(['Year','HS_Type','Tcode']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()



HS8_Month=Exchange_concated_final.groupby(['Year','Month','HS_Type','Tcode']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()






HS8_Total_Takh=Exchange_concated_final.groupby(['HS_Type','Tcode',' Takhsis_Type']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()

HS8_Year_Takh=Exchange_concated_final.groupby(['Year','HS_Type','Tcode',' Takhsis_Type']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()



HS8_Month_Takh=Exchange_concated_final.groupby(['Year','Month','HS_Type','Tcode',' Takhsis_Type']).agg(
    HS2 = ('HS2','first'),
    HS2_F = ('HS2_F','first'),
    HS2_E = ('HS2_E','first'),
    HS4 = ('HS4','first'),
    HS4_F = ('HS4_F','first'),
    HS4_E = ('HS4_E','first'),
    HS6 = ('HS6','first'),
    HS6_F = ('HS6_F','first'),
    HS6_E = ('HS6_E','first'),
    HS8_F = ('Tdesc','first'),
    MDollars = ('MDollars','sum')
).reset_index()

In [106]:
with pd.ExcelWriter(f"C:/TradeGroup/Reports/Arz_Takhsisi.xlsx") as writer:  

    Exchange_concated_final.to_excel(writer, sheet_name='Total_Raw', index=False)


    Takhsis_Type.to_excel(writer, sheet_name='Takhsis_Type', index=False)



    Month.to_excel(writer, sheet_name='Month', index=False)



    HS_Type.to_excel(writer, sheet_name='HS_Type', index=False)


    HS_Type_Month.to_excel(writer, sheet_name='HS_Type_Month', index=False)





    HS2_Total.to_excel(writer, sheet_name='HS2_Total', index=False)



    HS2_Year.to_excel(writer, sheet_name='HS2_Year', index=False)




    HS2_Month.to_excel(writer, sheet_name='HS2_Month', index=False)






    HS4_Total.to_excel(writer, sheet_name='HS4_Total', index=False)



    HS4_Year.to_excel(writer, sheet_name='HS4_Year', index=False)




    HS4_Month.to_excel(writer, sheet_name='HS4_Month', index=False)







    HS6_Total.to_excel(writer, sheet_name='HS6_Total', index=False)



    HS6_Year.to_excel(writer, sheet_name='HS6_Year', index=False)




    HS6_Month.to_excel(writer, sheet_name='HS6_Month', index=False)







    HS8_Total.to_excel(writer, sheet_name='HS8_Total', index=False)



    HS8_Year.to_excel(writer, sheet_name='HS8_Year', index=False)




    HS8_Month.to_excel(writer, sheet_name='HS8_Month', index=False)    







    HS8_Total_Takh.to_excel(writer, sheet_name='HS8_Total_Takh', index=False)



    HS8_Year_Takh.to_excel(writer, sheet_name='HS8_Year_Takh', index=False)




    HS8_Month_Takh.to_excel(writer, sheet_name='HS8_Month_Takh', index=False)