In [52]:
import pandas as pd
import numpy as np
import os
import openpyxl
import xlrd

In [53]:
# Set the working directory
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

def create_folder(folder_path):
    if not os.path.exists(f'{new_directory}/{folder_path}'):
        os.makedirs(f'{new_directory}/{folder_path}')
    else:
        print(f'Already Exists')

create_folder('Data/Indices')

Already Exists

In [54]:
Gorouh_Kalayi = pd.read_excel(f'C:/TradeGroup/Data/Indices/Kala_Asasi.xlsx')

Nerkh_Tarefe = pd.read_excel(f'C:/TradeGroup/Reports/3 ماه اول/Nerkh_Tarefe_Part2.xlsx',sheet_name="1403_03")


Nerkh_Tarefe =Nerkh_Tarefe[Nerkh_Tarefe['کد تعرفه']!='جمع کل']
Nerkh_Tarefe['کد تعرفه']= Nerkh_Tarefe['کد تعرفه'].astype('float')


new_column_names = ['Tcode', 'Weight', 'Value_R','Value_D','HV_041_R','Other_042_R',
                    'NN_043_R','TA_044_R','TM_045_R','J_046_R','M_047_R','A_048_R',
                    'THV_049_R','HSum_R','HPerc_R']

Nerkh_Tarefe = Nerkh_Tarefe.rename(columns=dict(zip(Nerkh_Tarefe.columns, new_column_names)))

Nerkh_Tarefe

,Tcode,Weight,Value_R,Value_D,HV_041_R,Other_042_R,NN_043_R,TA_044_R,TM_045_R,J_046_R,M_047_R,A_048_R,THV_049_R,HSum_R,HPerc_R
0,1012100.0,58150.00,3.482128e+11,1.629929e+06,14564020145,206691620,0,7848568938,26927882780,4326243,26927979406,7848617251,44092572,14726619193,4.229201
1,1022120.0,343895.00,2.994025e+11,1.050535e+06,9026984621,0,0,0,30089948740,0,30089948740,0,9026984621,0,0.000000
2,1022140.0,1500.00,2.421604e+10,8.496855e+04,726880441,7268804,0,748686855,1497373709,0,1497373709,748686855,0,734149245,3.031666
3,1022900.0,5171702.00,4.461138e+12,1.565312e+07,44834425313,14204529012,0,53090486297,393103046710,0,393103046710,53090486299,4398571442,54640382883,1.224808
4,1041090.0,41108.00,4.302674e+10,1.509710e+05,432418688,1703570,0,920976101,3160952447,0,3160952447,920976101,262061689,172060569,0.399892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4262,98871183.0,2743296.54,5.575018e+12,1.956147e+07,302496251080,77316009868,0,0,1009980443,570000000,541814962511,52927646202,15248889400,364563371548,6.539232
4263,98871184.0,234535.75,4.121875e+11,1.446272e+06,20967343745,3753808170,0,0,0,0,34333562727,8586241266,0,24721151915,5.997550
4264,98871192.0,129379.00,3.482248e+11,1.221842e+06,13945529182,455798025,0,0,0,0,30533347879,5725027995,0,14401327207,4.135640
4265,98871220.0,607243.15,9.731171e+11,3.414446e+06,49268105439,1034963720,0,0,0,0,103455323965,0,76974570,50226094589,5.161362
4266,98871290.0,451435.30,3.561025e+11,1.249483e+06,14494210503,334994558,0,0,0,0,32154279458,5153347874,21150223,14808054838,4.158368

In [55]:
my_data = Nerkh_Tarefe.merge(Gorouh_Kalayi,on='Tcode',how='left')

my_data['HS6'] = my_data['Tcode']//100

HS6s = pd.read_excel(f'C:/TradeGroup/Data/Dashboard/HSs_complete_Final31.xlsx')

my_data_new = my_data.merge(HS6s,on='HS6',how='left')

my_data_new.to_excel(f'C:/TradeGroup\Reports/Hoghough_Voroudi_HS8.xlsx',index=False)

In [59]:
Hoghough_Voroudi_Noe_Olaviat = my_data_new.groupby('Priority').agg(
    Import_D = ('Value_D','sum'),
    Import_R = ('Value_R','sum'),
    Hoghough_Voroudi_R = ('HSum_R','sum')
   # Hoghough_Voroudi_Perc = ('HPerc_R','mean')
).reset_index()


Hoghough_Voroudi_Noe_Olaviat['Darsad_Varedat']=round(100*Hoghough_Voroudi_Noe_Olaviat['Import_R']/Hoghough_Voroudi_Noe_Olaviat['Import_R'].sum(),3)
Hoghough_Voroudi_Noe_Olaviat['H_Perc'] = round(100*Hoghough_Voroudi_Noe_Olaviat['Hoghough_Voroudi_R']/Hoghough_Voroudi_Noe_Olaviat['Import_R'],3)


Hoghough_Voroudi_Noe_Olaviat.to_excel(f'C:/TradeGroup/Reports/Hoghough_Voroudi_Priority.xlsx',index=False)

In [61]:
my_data_new['isPrior']=np.where(my_data_new['Priority']=="21",1,0)

Hoghough_Voroudi_Prior = my_data_new.groupby('isPrior').agg(
    Import_D = ('Value_D','sum'),
    Import_R = ('Value_R','sum'),
    Hoghough_Voroudi_R = ('HSum_R','sum')
   # Hoghough_Voroudi_Perc = ('HPerc_R','mean')
).reset_index()
Hoghough_Voroudi_Prior['Darsad_Varedat']=round(100*Hoghough_Voroudi_Prior['Import_R']/Hoghough_Voroudi_Prior['Import_R'].sum(),3)
Hoghough_Voroudi_Prior['H_Perc'] =  round(100*Hoghough_Voroudi_Prior['Hoghough_Voroudi_R']/Hoghough_Voroudi_Prior['Import_R'],3)

Hoghough_Voroudi_Prior.to_excel(f'C:/TradeGroup/Reports/Hoghough_Voroudi_isPrior.xlsx',index=False)

In [63]:
my_data_new_isnotprior = my_data_new[my_data_new['isPrior']==0]

my_data_new_isnotprior

HS6s = my_data_new_isnotprior.groupby('HS6').agg(
    HS2_F = ('HS2_F','first'),
    HS4_F = ('HS4_F','first'),
    HS6_F = ('HS6_F','first'),
    Import_R = ('Value_R','sum'),
    Import_D = ('Value_D','sum'),

    Hoghough_Voroudi_R = ('HSum_R','sum')
).reset_index()
HS6s['Darsad_Varedat']=round(100*HS6s['Import_R']/HS6s['Import_R'].sum(),3)
HS6s['H_Perc'] = round(100*HS6s['Hoghough_Voroudi_R']/HS6s['Import_R'],3)

HS6s.to_excel(f'C:/TradeGroup/Reports/Hoghough_Voroudi_isnotPrior_HS6.xlsx',index=False)

In [64]:
my_data_new_isnotprior['HS4']=my_data_new_isnotprior['Tcode']//10000

my_data_new_isnotprior['HS2']=my_data_new_isnotprior['Tcode']//1000000

HS4s = my_data_new_isnotprior.groupby('HS4').agg(
    HS4_F = ('HS4_F','first'),
    HS6_F = ('HS6_F','first'),
    Import_R = ('Value_R','sum'),
    Import_D = ('Value_D','sum'),

    Hoghough_Voroudi_R = ('HSum_R','sum')
).reset_index()

HS4s['Darsad_Varedat']=round(100*HS4s['Import_R']/HS4s['Import_R'].sum(),3)
HS4s['H_Perc'] = round(100*HS4s['Hoghough_Voroudi_R']/HS4s['Import_R'],3)

HS4s.to_excel(f'C:/TradeGroup/Reports/Hoghough_Voroudi_isnotPrior_HS4.xlsx',index=False)




HS2s = my_data_new_isnotprior.groupby('HS2').agg(
    HS2_F = ('HS2_F','first'),
    Import_R = ('Value_R','sum'),
    Import_D = ('Value_D','sum'),

    Hoghough_Voroudi_R = ('HSum_R','sum')
).reset_index()

HS2s['Darsad_Varedat']=round(100*HS2s['Import_R']/HS2s['Import_R'].sum(),3)
HS2s['H_Perc'] = round(100*HS2s['Hoghough_Voroudi_R']/HS2s['Import_R'],3)

HS2s.to_excel(f'C:/TradeGroup/Reports/Hoghough_Voroudi_isnotPrior_HS2.xlsx',index=False)

C:\Users\msbirjandi\AppData\Local\Temp\ipykernel_12132\333103586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data_new_isnotprior['HS4']=my_data_new_isnotprior['Tcode']//10000
C:\Users\msbirjandi\AppData\Local\Temp\ipykernel_12132\333103586.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_data_new_isnotprior['HS2']=my_data_new_isnotprior['Tcode']//1000000