In [32]:
import pandas as pd
import numpy as np
import os

In [33]:
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

In [46]:
Iran_to_Indonasia=pd.read_excel(f"C:/TradeGroup/Reports/Iran-Indonasia-Alef.xlsx")
Iran_to_Indonasia['شماره تعرفه'].fillna(0,inplace=True)
Iran_to_Indonasia['HS8']=Iran_to_Indonasia['شماره تعرفه'].astype(int)
Iran_Exports_Codes = pd.unique(Iran_to_Indonasia['HS8'])
Iran_Exports_Codes

My_Excel_File=pd.ExcelFile(f"C:/TradeGroup/Reports/Iran-Indonasia-Be1.xlsx")
dfs = []
for sheet_name in My_Excel_File.sheet_names:
    df= My_Excel_File.parse(sheet_name)
    dfs.append(df)

The_Commodities = pd.concat(dfs,ignore_index=True)
The_Commodities.rename(columns={'شماره تعرفه':"HS8"},inplace=True)
The_Commodities['HS8']=pd.to_numeric(The_Commodities['HS8'])
Iran_Imports_Codes = pd.unique(The_Commodities['HS8'])

ValueError: Unable to parse string "۰۳۰۳۱۴۰۰" at position 1

In [37]:
Iran_Exports_Codes = Iran_Exports_Codes//100

In [28]:
Indonasia_Imports=pd.read_excel(f"C:/TradeGroup/Reports/Indonasia_Trademap.xlsx")

Indonasia_Imports

,Tcode,Product label,2018,2019,2020,2021,2022
0,271012,"Light oils and preparations, of petroleum or b...",11070557,9660709,5798710,10911906,17050775
1,270900,Petroleum oils and oils obtained from bitumino...,9161335,5704589,3391684,7047199,11455427
2,271019,"Medium oils and preparations, of petroleum or ...",6073455,3424153,2168814,3058564,6347809
3,100199,"Wheat and meslin (excl. seed for sowing, and d...",2570951,2799260,2616036,3548356,3810393
4,710812,"Gold, incl. gold plated with platinum, unwroug...",2125662,1765833,1898637,2675123,3517376
...,...,...,...,...,...,...,...
6409,940510,Chandeliers and other electric ceiling or wall...,40548,37504,32806,35969,0
6410,920300,Keyboard pipe organs; harmoniums and similar k...,0,0,0,0,0
6411,920410,Accordions and similar instruments,0,0,0,0,0
6412,920920,Mechanisms for musical boxes,0,0,0,0,0
6413,930521,"Smooth barrels for sporting, hunting and targe...",0,0,0,0,0

In [29]:
Indonasia_Imports['Trajihi'] = np.where(np.isin(Indonasia_Imports['Tcode'], Iran_Exports_Codes),1,0 )
Indonasia_Imports

,Tcode,Product label,2018,2019,2020,2021,2022,Trajihi
0,271012,"Light oils and preparations, of petroleum or b...",11070557,9660709,5798710,10911906,17050775,0
1,270900,Petroleum oils and oils obtained from bitumino...,9161335,5704589,3391684,7047199,11455427,0
2,271019,"Medium oils and preparations, of petroleum or ...",6073455,3424153,2168814,3058564,6347809,1
3,100199,"Wheat and meslin (excl. seed for sowing, and d...",2570951,2799260,2616036,3548356,3810393,0
4,710812,"Gold, incl. gold plated with platinum, unwroug...",2125662,1765833,1898637,2675123,3517376,0
...,...,...,...,...,...,...,...,...
6409,940510,Chandeliers and other electric ceiling or wall...,40548,37504,32806,35969,0,0
6410,920300,Keyboard pipe organs; harmoniums and similar k...,0,0,0,0,0,0
6411,920410,Accordions and similar instruments,0,0,0,0,0,0
6412,920920,Mechanisms for musical boxes,0,0,0,0,0,0
6413,930521,"Smooth barrels for sporting, hunting and targe...",0,0,0,0,0,0

In [30]:
Indonasia_Imports['Imports_Total'] = Indonasia_Imports[2018]+Indonasia_Imports[2019]+Indonasia_Imports[2020]+ Indonasia_Imports[2021]+ Indonasia_Imports[2022]
                                      
Indonasia_Imports.to_excel(f"C:/TradeGroup/Reports/Indonasia_Imports.xlsx", index= False)

In [20]:
Indonasia_Imports.columns

Index([        'Tcode', 'Product label',            2018,            2019,
                  2020,            2021,            2022,       'Trajihi',
       'Imports_Total'],
      dtype='object')