In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

In [3]:
year = 1403  
for year in range(1403,1404):
    exports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx"
    imports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Imports.xlsx"
    #if year!=1394:
    Exports = pd.read_excel(exports_file_path)
    Imports = pd.read_excel(imports_file_path)
    
    

    if "Year" not in Exports.columns:
        Exports['Year']= year
    if "Year" not in Imports.columns:
        Imports['Year']= year    

    if 'Month' not in Exports.columns:
        Exports['Month']= "Not_Available"
    if 'Month' not in Imports.columns:
        Imports['Month']= "Not_Available"



    if 'Custom' not in Exports.columns:
        Exports['Custom']= "Not_Available"
    if 'Custom' not in Imports.columns:
        Imports['Custom']= "Not_Available"
    

    Exports_mod1 = Exports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()


    Imports_mod1 = Imports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()

    Imports_mod1['Trade'] = "Import"
    Exports_mod1['Trade'] = "Export"

    Imports_mod1['Tcode'] = Imports_mod1['Tcode'].astype('int')
    Imports_mod1['HS6']=Imports_mod1['Tcode'].astype('str').str.slice(0,-2)

    Exports_mod1['Tcode'] = Exports_mod1['Tcode'].astype('int')
    Exports_mod1['HS6']=Exports_mod1['Tcode'].astype('str').str.slice(0,-2)

    Iran_Trade= pd.concat([Imports_mod1,Exports_mod1])

    if year == 1403:

        def get_nonzero_tdesc(tdesc, tcode):
            if tdesc == 0:
                nonzero_tdesc_rows = Iran_Trade.loc[(Iran_Trade['Tcode'] == tcode) & (Iran_Trade['Tdesc'] != 0)]
                if not nonzero_tdesc_rows.empty:
                    first_nonzero_tdesc = nonzero_tdesc_rows.iloc[0]['Tdesc']
                    return first_nonzero_tdesc
                else:
                    # If no non-zero Tdesc value is found for this Tcode, return the original value
                    return tdesc
            else:
                return tdesc

        # Apply the function to the Tdesc column
        Iran_Trade['Tdesc'] = Iran_Trade.apply(lambda row: get_nonzero_tdesc(row['Tdesc'], row['Tcode']), axis=1)


    Iran_Trade.to_excel(f'C:/TradeGroup/Data/Dashboard/IranTrade{year}.xlsx')

In [21]:
Iran_Trade

,Year,Tcode,Country,Custom,Month,Tdesc,Dollars,Rials,Weight,Trade,HS6
0,1402,1012100,بلغارستان,بازرگان,Not_Available,حیوانات مولد نژاد خالص,466720,132838362000,22200,Import,10121
1,1402,1012100,هلند,بازرگان,Not_Available,حیوانات مولد نژاد خالص,482553,135564215100,19800,Import,10121
2,1402,1012100,هلند,تهران,Not_Available,حیوانات مولد نژاد خالص,31073,8855712000,1500,Import,10121
3,1402,1012100,هلند,فرودگاه امام خميني (ره),Not_Available,حیوانات مولد نژاد خالص,1520942,384982293200,53300,Import,10121
4,1402,1022120,افغانستان,بازارچه ميلک,Not_Available,گاو گوشتی مولد نژاد خالص,350857,99994245000,139711,Import,10221
...,...,...,...,...,...,...,...,...,...,...,...
56465,1402,98842940,عراق,تمرچين پيرانشهر,Not_Available,قطعات منفصله برای تولید ماشین آلات راهسازی، به...,111803,41991131350,45896,Export,988429
56466,1402,98843310,عراق,مهران,Not_Available,با ساخت داخل تا 30 درصد,79369,30425551200,19800,Export,988433
56467,1402,98843320,عراق,تمرچين پيرانشهر,Not_Available,قطعات منفصله برای تولید کمباین، به استثنای لاس...,666198,257815050302,175831,Export,988433
56468,1402,98870119,عراق,تمرچين پيرانشهر,Not_Available,با ساخت داخل 51% و بیشتر,814847,306155395316,301257,Export,988701
56469,1402,98870314,چين,منطقه ويژه اقتصادي بم,Not_Available,قطعات منفصله جهت تولید اتومبیل سواری ردیف 8703...,6338,2526696396,382,Export,988703

In [15]:
year = 1402
exports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx"
imports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Imports.xlsx"
#if year!=1394:
Exports = pd.read_excel(exports_file_path)
Imports = pd.read_excel(imports_file_path)

Imports

,Tcode,Custom,Country,Tcode.1,Tdesc,Weight,Rials,Dollars
0,1402,منطقه ويژه اقتصادي پيام,امارات متحده عربي,7132030,نخود معمولی غلافدار خشک، غلاف کنده، حتی پوست ک...,220740,84434932020,296263
1,1402,منطقه ويژه اقتصادي پيام,امارات متحده عربي,7133310,لوبیا چیتی,456000,159940423958,561194
2,1402,منطقه ويژه اقتصادي پيام,امارات متحده عربي,9011190,قهوه، بونداده كافئین نگرفته غیر مذكور,38400,26819942400,94105
3,1402,منطقه ويژه اقتصادي پيام,امارات متحده عربي,12060090,دانه آفتابگردان حتی خرد شده غیر مذکور,482000,172356216642,604759
4,1402,منطقه ويژه اقتصادي پيام,امارات متحده عربي,18050090,پودر كاكائو بدون افزودن قند، شكر یا سایر مواد ...,103000,81769188600,286909
...,...,...,...,...,...,...,...,...
62994,1402,منطقه ويژه اقتصادي سلفچگان,تايوان,35069190,چسب گرما ذوب بر اساس پلیمرهای مشمول شماره 3901...,159088,104093215270,365239
62995,1402,منطقه ويژه اقتصادي سلفچگان,تايوان,39100090,سایر,76,188564312,662
62996,1402,منطقه ويژه اقتصادي سلفچگان,تايوان,39239090,سایر غیر از ردیف های مشمول ردیف های 39231000 ل...,1297,1074110230,3769
62997,1402,منطقه ويژه اقتصادي سلفچگان,تايوان,40169300,درز بند، واشر و سایر درزگیرها از کائوچوی ولکان...,667,4931413353,17303
62998,1402,منطقه ويژه اقتصادي سلفچگان,تايوان,48192090,سایر کارتن قوطی وجعبه، تاشو از کاغذ یا مقوای غ...,238,155089540,544

In [9]:
Exports_mod1 = Exports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()


Imports_mod1 = Imports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()

Imports_mod1['Trade'] = "Import"
Exports_mod1['Trade'] = "Export"

Iran_Trade= pd.concat([Imports_mod1,Exports_mod1])

Iran_Trade

,Year,Tcode,Country,Custom,Month,Tdesc,Dollars,Rials,Weight,Trade
0,1403,1012100,آلمان,فرودگاه امام خميني (ره),2,حیوانات مولد نژاد خالص,342373,97576444000,14500,Import
1,1403,1012100,بلغارستان,بازرگان,1,حیوانات مولد نژاد خالص,239533,68266880000,9000,Import
2,1403,1012100,بلغارستان,بازرگان,2,حیوانات مولد نژاد خالص,143895,41009963500,6000,Import
3,1403,1012100,بلغارستان,بازرگان,5,حیوانات مولد نژاد خالص,162318,46260769000,7100,Import
4,1403,1012100,بلغارستان,بازرگان,6,حیوانات مولد نژاد خالص,63164,18001626000,3000,Import
...,...,...,...,...,...,...,...,...,...,...
91163,1403,98843320,عراق,تمرچين پيرانشهر,6,قطعات منفصله برای تولید کمباین، به استثنای لاس...,45090,20602710000,25440,Export
91164,1403,98870311,چين,منطقه ويژه اقتصادي بم,4,قطعات منفصله جهت تولید اتومبیل سواری ردیف 8703...,1997,857874144,590,Export
91165,1403,98870312,افغانستان,دوغارون,1,قطعات منفصله جهت تولید اتومبیل سواری ردیف 8703...,3640,1476118280,910,Export
91166,1403,98870312,افغانستان,دوغارون,2,قطعات منفصله جهت تولید اتومبیل سواری ردیف 8703...,-3640,-1476118280,-910,Export
91167,1403,98870312,افغانستان,دوغارون,3,قطعات منفصله جهت تولید اتومبیل سواری ردیف 8703...,6434,2714330736,1612,Export

In [14]:
year = 14
for year in range(1403,1404):
    exports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx"
    imports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Imports.xlsx"
    #if year!=1394:
    Exports = pd.read_excel(exports_file_path)
    Imports = pd.read_excel(imports_file_path)
    
    

    if "Year" not in Exports.columns:
        Exports['Year']= year
    if "Year" not in Imports.columns:
        Imports['Year']= year    

    if 'Month' not in Exports.columns:
        Exports['Month']= "Not_Available"
    if 'Month' not in Imports.columns:
        Imports['Month']= "Not_Available"



    if 'Custom' not in Exports.columns:
        Exports['Custom']= "Not_Available"
    if 'Custom' not in Imports.columns:
        Imports['Custom']= "Not_Available"
    

    Exports_mod1 = Exports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()


    Imports_mod1 = Imports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()

    Imports_mod1['Trade'] = "Import"
    Exports_mod1['Trade'] = "Export"

    Imports_mod1['Tcode'] = Imports_mod1['Tcode'].astype('int')
    Imports_mod1['HS6']=Imports_mod1['Tcode'].astype('str')

    Exports_mod1['Tcode'] = Exports_mod1['Tcode'].astype('int')
    Exports_mod1['HS6']=Exports_mod1['Tcode'].astype('str')

    Iran_Trade= pd.concat([Imports_mod1,Exports_mod1])

    Iran_Trade.to_excel(f'C:/TradeGroup/Data/Dashboard/IranTrade{year}.xlsx')

In [28]:
year = 14
for year in range(1371,1375):
    exports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx"
    imports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Imports.xlsx"
    #if year!=1394:
    Exports = pd.read_excel(exports_file_path)
    Imports = pd.read_excel(imports_file_path)
    
    

    if "Year" not in Exports.columns:
        Exports['Year']= year
    if "Year" not in Imports.columns:
        Imports['Year']= year    

    if 'Month' not in Exports.columns:
        Exports['Month']= "Not_Available"
    if 'Month' not in Imports.columns:
        Imports['Month']= "Not_Available"



    if 'Custom' not in Exports.columns:
        Exports['Custom']= "Not_Available"
    if 'Custom' not in Imports.columns:
        Imports['Custom']= "Not_Available"
    

    Exports_mod1 = Exports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()


    Imports_mod1 = Imports.groupby(['Year','Tcode','Country','Custom','Month']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()

    Imports_mod1['Trade'] = "Import"
    Exports_mod1['Trade'] = "Export"

    Imports_mod1['Tcode'] = Imports_mod1['Tcode']//100
    Imports_mod1['HS6']=Imports_mod1['Tcode']//100

    Exports_mod1['Tcode'] = Exports_mod1['Tcode']//100
    Exports_mod1['HS6']=Exports_mod1['Tcode']//100

    Iran_Trade= pd.concat([Imports_mod1,Exports_mod1])

    Iran_Trade.to_excel(f'C:/TradeGroup/Data/Dashboard/IranTrade{year}.xlsx')

In [13]:
year = 1383
exports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx"
imports_file_path = f"{my_wd}/Data/Cleaned_Data/Y{year}Imports.xlsx"
#if year!=1394:
Exports = pd.read_excel(exports_file_path)
Imports = pd.read_excel(imports_file_path)



if "Year" not in Exports.columns:
    Exports['Year']= year
if "Year" not in Imports.columns:
    Imports['Year']= year    

if 'Month' not in Exports.columns:
    Exports['Month']= np.nan
if 'Month' not in Imports.columns:
    Imports['Month']= np.nan



if 'Custom' not in Exports.columns:
    Exports['Custom']= np.nan
if 'Custom' not in Imports.columns:
    Imports['Custom']= np.nan

In [20]:

Exports_mod1 = Exports.groupby(['Year','Tcode','Country','Custom']).agg(
        Tdesc = ('Tdesc','first'),
        Dollars = ("Dollars",'sum'),
        Rials = ('Rials','sum'),
        Weight = ('Weight','sum')
    ).reset_index()

,Year,Tcode,Country,Custom,Tdesc,Dollars,Rials,Weight
0,1383,1019090.0,افغانستان,دوغارون,ا سب ا لاغ قاطر وا ستر زنده به جز مولدنژا ...,18919.30,1.608140e+08,22230.0
1,1383,1021090.0,افغانستان,مشهد,گاو مولد نژا د خاص بجز گاو شيري,8313.09,7.066125e+07,1650.0
2,1383,1029090.0,افغانستان,مشهد,ساير گاوها بجز گاوشيري و مولد نژا دخاص,67398.78,5.728896e+08,22840.0
3,1383,1029090.0,افغانستان,مشهد(سپاد),ساير گاوها بجز گاوشيري و مولد نژا دخاص,194055.16,1.649469e+09,39150.0
4,1383,1041000.0,امارات متحده عربي,شهيد باهنر,حيوا نات زنده ا ز نوع گوسفند,8014321.05,6.812173e+10,3088730.0
...,...,...,...,...,...,...,...,...
26942,1383,98870341.0,جمهوري كره,شهيدرجايي,جهت توليدخودروهاي سوا ري کاربا ساخت دا خل ...,18314.29,1.556715e+08,2080.0
26943,1383,98870365.0,امارات متحده عربي,تجاري مهراباد,جهت توليدخودروهاي سوا ري کاربا ساخت دا خل ...,1519.94,1.291950e+07,1500.0
26944,1383,98870366.0,اسپانيا,تجاري مهراباد,جهت توليدخودروهاي سوا ري کاربا ساخت دا خل ...,611.08,5.194200e+06,150.0
26945,1383,98870444.0,امارات متحده عربي,تجاري مهراباد,برا ي توليدکاميون و کاميونت با ساخت دا خل ...,5137.93,4.367248e+07,2780.0
26946,1383,98870444.0,جمهوري كره,شهيدرجايي,برا ي توليدکاميون و کاميونت با ساخت دا خل ...,11347.57,9.645434e+07,4118.0