In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

def create_folder(folder_path):
    if not os.path.exists(f'{new_directory}/{folder_path}'):
        os.makedirs(f'{new_directory}/{folder_path}')
    else:
        print(f'Already Exists')

create_folder('Data/Indices')

Already Exists

In [6]:
baseyear = 1392
for year in range(1392,1403):
    Data = pd.read_excel(f"{my_wd}/Data/Cleaned_Data/Y{year}Exports.xlsx")
    Data = Data.dropna(subset=['Tcode'])
    colname = f'Dollars_Exp_{year}'
    Data['HS6'] = Data['Tcode']//100
    Data_HS6 = Data.groupby('HS6').agg(
    Dollars = (f'Dollars','sum')
    ).reset_index()



    #Data_HS6.columns.str.replace("Dollars",f'Dollars_Exp_{year}',inplace=True)
    Data_HS6.columns = Data_HS6.columns.str.replace("Dollars", f"Dollars_Exp_{year}")
    Data_HS6[f'Sign_{year}']=np.where(Data_HS6[f"Dollars_Exp_{year}"]>10000,1,0)
    Data_HS6.to_excel(f'{my_wd}/Data/Indices/Exports_{year}_HS6.xlsx', index = False)    
    if year == baseyear:
        TimeSeries = Data_HS6[Data_HS6[f'Sign_{year}']==1]
        TimeSeries['Persistency']=TimeSeries[f'Sign_{year}']
        #TimeSeries = TimeSeries[TimeSeries['Persistency']==1]
        counter= 0
    else:
        counter = counter + 1
        TimeSeries = TimeSeries.merge(Data_HS6,on="HS6",how='left')
        TimeSeries.fillna(0,inplace=True) 
        TimeSeries['Persistency_Helper']= TimeSeries['Persistency']
        TimeSeries['Persistency']=np.where((TimeSeries['Persistency_Helper']== counter) &
                                            (TimeSeries[f'Sign_{year}']>0),
                                             TimeSeries['Persistency_Helper']+1,
                                             TimeSeries['Persistency_Helper'])

C:\Users\msbirjandi\AppData\Local\Temp\ipykernel_12764\3265993861.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TimeSeries['Persistency']=TimeSeries[f'Sign_{year}']

In [9]:
TimeSeries

,HS6,Dollars_Exp_1392,Sign_1392,Persistency,Dollars_Exp_1393,Sign_1393,Persistency_Helper,Dollars_Exp_1394,Sign_1394,Dollars_Exp_1395,...,Dollars_Exp_1398,Sign_1398,Dollars_Exp_1399,Sign_1399,Dollars_Exp_1400,Sign_1400,Dollars_Exp_1401,Sign_1401,Dollars_Exp_1402,Sign_1402
0,10221.0,466556.37,1,7,11247198.14,1.0,7,1.664361e+07,1.0,5.041617e+06,...,2.331740e+05,1.0,0.0,0.0,0.0,0.0,1408711.0,1.0,1493588.0,1.0
1,10511.0,11162794.87,1,8,12916414.04,1.0,8,8.687611e+06,1.0,7.212107e+06,...,1.377338e+06,1.0,4113851.0,1.0,8550.0,0.0,1974263.0,1.0,160440.0,1.0
2,10512.0,3473830.53,1,3,57097.00,1.0,3,1.490999e+05,1.0,0.000000e+00,...,0.000000e+00,0.0,47292.0,1.0,13975.0,1.0,28600.0,1.0,14925.0,1.0
3,10613.0,274053.19,1,11,195255.00,1.0,10,9.379861e+04,1.0,2.388960e+05,...,5.678371e+04,1.0,284000.0,1.0,952435.0,1.0,1899387.0,1.0,1541192.0,1.0
4,10631.0,26079.00,1,1,5860.00,0.0,1,5.878731e+04,1.0,1.153000e+04,...,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2201,961900.0,4933804.35,1,11,3617195.86,1.0,10,3.775321e+06,1.0,5.507692e+06,...,6.886766e+06,1.0,11085522.0,1.0,8433880.0,1.0,7739073.0,1.0,11702933.0,1.0
2202,970110.0,35763.50,1,10,13282.00,1.0,10,6.104910e+05,1.0,2.942680e+05,...,9.341796e+04,1.0,48112.0,1.0,176335.0,1.0,27182.0,1.0,0.0,0.0
2203,970190.0,40241.19,1,10,81396.04,1.0,10,1.912310e+05,1.0,8.935000e+04,...,5.327277e+04,1.0,82230.0,1.0,92196.0,1.0,26770.0,1.0,0.0,0.0
2204,988701.0,82552.00,1,1,1818.00,0.0,1,4.847373e+05,1.0,2.186180e+05,...,1.725000e+04,1.0,638.0,0.0,44594.0,1.0,149291.0,1.0,814848.0,1.0
2205,988703.0,7118876.00,1,11,44253680.12,1.0,10,9.076492e+07,1.0,1.265911e+07,...,2.180196e+07,1.0,3517814.0,1.0,5777390.0,1.0,3333908.0,1.0,43383.0,1.0

In [8]:
TimeSeries.to_excel(f'{my_wd}/Data/Indices/Persistency_HS6_Detailed.xlsx',index = False)


TimeSeries_Uniques = TimeSeries.groupby('Persistency').agg(
    Persistency_Count = ('Persistency','count')
).reset_index()

TimeSeries_Uniques['Countinues_Years'] = np.where(TimeSeries_Uniques['Persistency']>0,TimeSeries_Uniques['Persistency']-1,0)

TimeSeries_Uniques.to_excel(f'{my_wd}/Data/Indices/Persistency_HS6.xlsx',index = False)

TimeSeries_Uniques

    Persistency  Persistency_Count  Countinues_Years
0             1                375                 0
1             2                201                 1
2             3                126                 2
3             4                 96                 3
4             5                 43                 4
5             6                 75                 5
6             7                 58                 6
7             8                 39                 7
8             9                 28                 8
9            10                 44                 9
10           11               1121                10