In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set the working directory
os.chdir("C:\TradeGroup")
my_wd = os.getcwd()
new_directory = my_wd

def create_folder(folder_path):
    if not os.path.exists(f'{new_directory}/{folder_path}'):
        os.makedirs(f'{new_directory}/{folder_path}')
    else:
        print(f'Already Exists')

create_folder('Data/Indices')

Already Exists

In [3]:
Iran_Exports = pd.read_excel(f'{my_wd}/Data/Indices/Trademap_IranExports_2022.xlsx')
Iran_Exports['Code'] = Iran_Exports['Code'].str.replace("'","").astype('int')
#Iran_Exports['Code'] = Iran_Exports['Code'].astype("int")

remaining_columns = Iran_Exports.columns[2:]


remaining_columns=remaining_columns.str.replace("Exported value in ","")

Iran_Exports.columns=Iran_Exports.columns.str.replace("Exported value in ","")

Iran_Exports.columns = Iran_Exports.columns[0:2].tolist() + [col + '_Iran_Exports' for col in Iran_Exports.columns[2:]]

In [23]:
Countries = ['China','Turkey','Russia','SKorea',
             'Iraq',
             'Indonasia','Syria', 'Armenia', 'Belarus', 'Kazakhstan', 'Kyrgyzstan']

for country in Countries:
    Country_Imports=f'{country}_Imports'
    print(Country_Imports)
    
    globals()[Country_Imports]=pd.read_excel(f'{my_wd}/Data/Indices/Trademap_{country}Imports_2023.xlsx')
    
    if (globals()[Country_Imports]['Code'].dtype != "int") and (globals()[Country_Imports]['Code'].dtype == "object"):
        globals()[Country_Imports]['Code'] = globals()[Country_Imports]['Code'].str.replace("'","").astype('int')
    #globals()[Country_Imports]['Code'] = globals()[Country_Imports]['Code'].astype("int")
    
    remaining_columns = globals()[Country_Imports].columns[1:]
    remaining_columns=remaining_columns.str.replace("Imported value in ","")

    globals()[Country_Imports].columns=globals()[Country_Imports].columns.str.replace("Imported value in ","")

    globals()[Country_Imports].columns = globals()[Country_Imports].columns[0:1].tolist() + [col + f'_{country}_Imports' for col in globals()[Country_Imports].columns[1:]]

    Iran_Country_All=f'Iran_{country}_All'
    Iran_Country_All_filledNAs=f'Iran_{country}_All_filledNAs'

    globals()[Country_Imports]["Code"] = globals()[Country_Imports]['Code'].astype(int)

    globals()[Iran_Country_All] = Iran_Exports.merge(globals()[Country_Imports],on=["Code"],how= "outer")
    globals()[Iran_Country_All_filledNAs]=globals()[Iran_Country_All].fillna(0)

China_Imports
Turkey_Imports
Russia_Imports
SKorea_Imports
Iraq_Imports
Indonasia_Imports
Syria_Imports
Armenia_Imports
Belarus_Imports
Kazakhstan_Imports
Kyrgyzstan_Imports

In [25]:
Irans_Potential = pd.DataFrame({"Country": ['China','Turkey','Russia','SKorea','Iraq','Indonasia','Syria','Armenia','Belarus', 'Kazakhstan', 'Kyrgyzstan']})
for country in Countries:
    full_dataframe_name=f'Iran_{country}_All_filledNAs'
    if (country!='Iraq')&(country!='Armenia')&(country!='Belarus')&(country!='Kazakhstan')&(country!='Kyrgyzstan'):
        for year in range(2009,2023):

            globals()[full_dataframe_name][f'{year}_Potential'] = globals()[full_dataframe_name][[f'{year}_Iran_Exports', f'{year}_{country}_Imports']].min(axis=1)
            Irans_Potential.loc[Irans_Potential['Country'] == country, f'{year}'] = globals()[full_dataframe_name][f'{year}_Potential'].sum()
    else:
        for year in range(2014,2023):

            globals()[full_dataframe_name][f'{year}_Potential'] = globals()[full_dataframe_name][[f'{year}_Iran_Exports', f'{year}_{country}_Imports']].min(axis=1)
            Irans_Potential.loc[Irans_Potential['Country'] == country, f'{year}'] = globals()[full_dataframe_name][f'{year}_Potential'].sum()        
#globals()[full_dataframe_name]["Column3"].sum()

In [26]:
Irans_Potential.to_excel(f'{my_wd}\Data\Indices\Irans_Potential.xlsx',index=False)

It needs to be multiplied by 0.3

***

The code is ended. From now on are previous codes and are just good for understanding globals().

***

In [20]:
China_Imports = pd.read_excel(f'{my_wd}/Data/Indices/Trademap_ChinaImports_2023.xlsx')

China_Imports['Code'] = China_Imports['Code'].str.replace("'","")
China_Imports['Code'] = China_Imports['Code'].astype("int")


remaining_columns = China_Imports.columns[2:]


remaining_columns=remaining_columns.str.replace("Imported value in ","")

China_Imports.columns=China_Imports.columns.str.replace("Imported value in ","")

China_Imports.columns = China_Imports.columns[0:2].tolist() + [col + '_China_Imports' for col in China_Imports.columns[2:]]


China_Imports

,Code,Product label,2004_China_Imports,2005_China_Imports,2006_China_Imports,2007_China_Imports,2008_China_Imports,2009_China_Imports,2010_China_Imports,2011_China_Imports,...,2014_China_Imports,2015_China_Imports,2016_China_Imports,2017_China_Imports,2018_China_Imports,2019_China_Imports,2020_China_Imports,2021_China_Imports,2022_China_Imports,2023_China_Imports
0,270900,Petroleum oils and oils obtained from bitumino...,33911681,47722764,66411903,79858329,129330933,89255587,135299673,196770605,...,228288472,134341241,116171247,162191057,239222367,242384863,178452855,258053155,365512020,336481110
1,854231,Electronic integrated circuits as processors a...,0,0,0,79773525,80904547,70947528,86053448,98088893,...,105226923,108220599,104900300,111363038,127430722,143736462,171410280,203390671,205091244,176701021
2,260111,Non-agglomerated iron ores and concentrates (e...,10866474,15954914,18859400,30937515,57069520,47047802,75985788,105553154,...,90751176,55691375,55927221,74278723,72674453,97352694,117933229,177711835,125476255,130576256
3,710812,"Gold, incl. gold plated with platinum, unwroug...",0,0,0,0,0,0,0,0,...,0,0,0,0,43120648,41085121,10917274,46380120,75714664,90290276
4,854239,Electronic integrated circuits (excl. such as ...,0,0,0,19465807,22052284,23680270,30886501,31336286,...,49134247,49437168,48698284,48614337,51691958,57400951,70980888,91571374,93876375,82151510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,852410,Gramophone records,1180,181,173,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6413,851712,"Telephones for cellular networks ""mobile telep...",0,0,0,1868554,1858359,1784202,1141524,1283333,...,1793077,3442535,2537869,748048,292741,438153,898319,1315894,69,0
6414,851719,Line telephone sets; videophones (excluding li...,26470,23521,22237,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6415,851921,Record players without loudspeaker,150,273,13,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6416,852330,Cards incorporating an unrecorded magnetic stripe,7075,865,489,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
Turkey_Imports = pd.read_excel(f'{my_wd}/Data/Indices/Trademap_TurkiyeImports_2023.xlsx')

Turkey_Imports['Code'] = Turkey_Imports['Code'].str.replace("'","")
Turkey_Imports['Code'] = Turkey_Imports['Code'].astype("int")


remaining_columns = Turkey_Imports.columns[2:]


remaining_columns=remaining_columns.str.replace("Imported value in ","")

Turkey_Imports.columns=Turkey_Imports.columns.str.replace("Imported value in ","")

Turkey_Imports.columns = Turkey_Imports.columns[0:2].tolist() + [col + '_Turkey_Imports' for col in Turkey_Imports.columns[2:]]

Turkey_Imports

,Code,Product label,2004_Turkey_Imports,2005_Turkey_Imports,2006_Turkey_Imports,2007_Turkey_Imports,2008_Turkey_Imports,2009_Turkey_Imports,2010_Turkey_Imports,2011_Turkey_Imports,...,2014_Turkey_Imports,2015_Turkey_Imports,2016_Turkey_Imports,2017_Turkey_Imports,2018_Turkey_Imports,2019_Turkey_Imports,2020_Turkey_Imports,2021_Turkey_Imports,2022_Turkey_Imports,2023_Turkey_Imports
0,999999,Commodities not elsewhere specified,10738314,15932581,21358447,24542452,34131572,19125400,24383848,35423236,...,35475628,25065939,16352330,22592897,25005291,27967481,18773036,34048075,65495616,39545207
1,710812,"Gold, incl. gold plated with platinum, unwroug...",2395052,3526547,4011937,5323890,4988870,1615410,2495110,6125781,...,7104889,3423866,6456908,16576283,11298656,11265796,25179298,5493192,20433570,29569392
2,271019,"Medium oils and preparations, of petroleum or ...",1863292,2895263,4645566,6127407,9688454,7338862,9636253,13066846,...,15192689,8211162,6626092,8915295,11684206,8743058,5946187,9608343,18303764,19849102
3,720449,"Waste and scrap of iron or steel (excl. slag, ...",2994223,3140794,3908025,5585808,8959396,4238705,7118439,9613153,...,6892992,4258008,3904386,6056670,7061333,5555510,6061417,10777646,9548225,7551546
4,870322,Motor cars and other motor vehicles principall...,872429,684941,470848,496850,615767,861363,1102732,1125260,...,1162211,1608463,1878773,1466682,933201,622586,2206945,2175899,2916434,6660258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362,851730,Telephonic or telegraphic switching apparatus,19544,75181,61613,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6363,851790,Parts of electrical apparatus for line telepho...,224137,205481,179851,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6364,851410,Resistance heated industrial or laboratory fur...,11223,9471,11138,25642,22610,38642,15694,32290,...,33350,30671,21538,21747,29454,23997,19051,34590,0,0
6365,850880,"Electro-mechanical tools, for working in the h...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6366,850930,"Domestic kitchen waste disposers, with self-co...",478,508,629,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
Iran_China_All = Iran_Exports.merge(China_Imports,on=["Code","Product label"],how= "outer")
Iran_China_All_filledNAs=Iran_China_All.fillna(0)

Iran_China_All_filledNAs

,Code,Product label,2003_Iran_Exports,2004_Iran_Exports,2005_Iran_Exports,2006_Iran_Exports,2007_Iran_Exports,2008_Iran_Exports,2009_Iran_Exports,2010_Iran_Exports,...,2014_China_Imports,2015_China_Imports,2016_China_Imports,2017_China_Imports,2018_China_Imports,2019_China_Imports,2020_China_Imports,2021_China_Imports,2022_China_Imports,2023_China_Imports
0,270900,Petroleum oils and oils obtained from bitumino...,26124000.0,34289000.0,48286000.0,50223930.0,60382065.0,81415379.0,49408527.0,72350088.0,...,228288472.0,134341241.0,116171247.0,162191057.0,239222367.0,242384863.0,178452855.0,258053155.0,365512020.0,336481110.0
1,271000,Petroleum oils and oils obtained from bitumino...,0.0,0.0,0.0,0.0,7864367.0,7510337.0,6279883.0,9682267.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,271112,"Propane, liquefied",212939.0,209251.0,262450.0,655989.0,972457.0,1150711.0,968805.0,1422892.0,...,3986548.0,4412636.0,4397228.0,6663114.0,7896298.0,7357164.0,6556170.0,12649292.0,16019429.0,15849568.0
3,310210,"Urea, whether or not in aqueous solution (excl...",13302.0,3928.0,0.0,0.0,0.0,36467.0,111424.0,431656.0,...,3049.0,3692.0,15948.0,29888.0,45433.0,46544.0,1696.0,28392.0,3433.0,2786.0
4,290511,"Methanol ""methyl alcohol""",846.0,27531.0,193184.0,163880.0,632725.0,903917.0,649704.0,1048625.0,...,1611676.0,1561285.0,2098217.0,2640785.0,2923811.0,2909453.0,2684798.0,3860106.0,4165363.0,4170728.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6460,811231,"Unwrought hafnium and hafnium waste, scrap and...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,375.0,0.0
6461,846912,"Typewriters, automatic (excluding word-process...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6462,847971,"Passenger boarding bridges, of a kind used in ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6.0,0.0,85.0,0.0,57.0,0.0,0.0,0.0
6463,852731,"Radio-broadcast receivers, for mains operation...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6464,851921,Record players without loudspeaker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:

Iran_Turkey_All = Iran_Exports.merge(Turkey_Imports,on=["Code","Product label"],how= "outer")
Iran_Turkey_All_filledNAs=Iran_Turkey_All.fillna(0)

Iran_Turkey_All_filledNAs

,Code,Product label,2003_Iran_Exports,2004_Iran_Exports,2005_Iran_Exports,2006_Iran_Exports,2007_Iran_Exports,2008_Iran_Exports,2009_Iran_Exports,2010_Iran_Exports,...,2014_Turkey_Imports,2015_Turkey_Imports,2016_Turkey_Imports,2017_Turkey_Imports,2018_Turkey_Imports,2019_Turkey_Imports,2020_Turkey_Imports,2021_Turkey_Imports,2022_Turkey_Imports,2023_Turkey_Imports
0,270900,Petroleum oils and oils obtained from bitumino...,26124000.0,34289000.0,48286000.0,50223930.0,60382065.0,81415379.0,49408527.0,72350088.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,271000,Petroleum oils and oils obtained from bitumino...,0.0,0.0,0.0,0.0,7864367.0,7510337.0,6279883.0,9682267.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,271112,"Propane, liquefied",212939.0,209251.0,262450.0,655989.0,972457.0,1150711.0,968805.0,1422892.0,...,76278.0,39799.0,37005.0,62486.0,63672.0,50028.0,37310.0,107078.0,122882.0,125107.0
3,310210,"Urea, whether or not in aqueous solution (excl...",13302.0,3928.0,0.0,0.0,0.0,36467.0,111424.0,431656.0,...,607704.0,461484.0,507696.0,679049.0,593052.0,711715.0,587862.0,1136453.0,1695848.0,1253610.0
4,290511,"Methanol ""methyl alcohol""",846.0,27531.0,193184.0,163880.0,632725.0,903917.0,649704.0,1048625.0,...,246069.0,172249.0,120581.0,205228.0,242231.0,142298.0,118479.0,235246.0,236116.0,158634.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,841121,Turbopropellers of a power <= 1.100 kW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,597.0,875.0,1396.0,9333.0,3613.0,17680.0,6010.0,1750.0,62046.0,0.0
6418,846920,"Typewriters, electric (excluding automatic typ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6419,851910,Coin-operated or disc-operated record-players,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6420,851931,"Turntables ""record-decks"", with automatic reco...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6421,851940,Transcribing machines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
Irans_Potential = pd.DataFrame({"Country": ["China","Turkey"]})
for country in ['China','Turkey']:
    full_dataframe_name=f'Iran_{country}_All_filledNAs'
    for year in range(2009,2023):

        globals()[full_dataframe_name][f'{year}_Potential'] = globals()[full_dataframe_name][[f'{year}_Iran_Exports', f'{year}_{country}_Imports']].min(axis=1)
        Irans_Potential.loc[Irans_Potential['Country'] == country, f'{year}'] = globals()[full_dataframe_name][f'{year}_Potential'].sum()

#globals()[full_dataframe_name]["Column3"].sum()


Irans_Potential

,Country,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,China,62887670.0,89799245.0,108537827.0,103935711.0,67850381.0,63100108.0,39401615.0,59871628.0,74518932.0,78748657.0,34239557.0,27399616.0,56219859.0,58970577.0
1,Turkey,8959214.0,10889174.0,14397470.0,12846745.0,13636474.0,14332816.0,13781647.0,13457665.0,15130499.0,16074367.0,11980345.0,11109096.0,20003094.0,22009740.0

In [48]:
Iran_China_All_filledNAs

,Code,Product label,2003_Iran_Exports,2004_Iran_Exports,2005_Iran_Exports,2006_Iran_Exports,2007_Iran_Exports,2008_Iran_Exports,2009_Iran_Exports,2010_Iran_Exports,...,2013_Potential,2014_Potential,2015_Potential,2016_Potential,2017_Potential,2018_Potential,2019_Potential,2020_Potential,2021_Potential,2022_Potential
0,270900,Petroleum oils and oils obtained from bitumino...,26124000.0,34289000.0,48286000.0,50223930.0,60382065.0,81415379.0,49408527.0,72350088.0,...,46904434.0,38938377.0,19257358.0,35074034.0,47186277.0,50823249.0,16153935.0,10034998.0,19069411.0,22485850.0
1,271000,Petroleum oils and oils obtained from bitumino...,0.0,0.0,0.0,0.0,7864367.0,7510337.0,6279883.0,9682267.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,271112,"Propane, liquefied",212939.0,209251.0,262450.0,655989.0,972457.0,1150711.0,968805.0,1422892.0,...,1240159.0,2370838.0,1419080.0,1221624.0,1474971.0,1710220.0,0.0,0.0,1907622.0,3633154.0
3,310210,"Urea, whether or not in aqueous solution (excl...",13302.0,3928.0,0.0,0.0,0.0,36467.0,111424.0,431656.0,...,10903.0,3049.0,3692.0,15948.0,29888.0,45433.0,46544.0,1696.0,28392.0,3433.0
4,290511,"Methanol ""methyl alcohol""",846.0,27531.0,193184.0,163880.0,632725.0,903917.0,649704.0,1048625.0,...,1074056.0,1470425.0,878424.0,932629.0,1178360.0,1349965.0,1114514.0,1174848.0,2200175.0,2385071.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6460,811231,"Unwrought hafnium and hafnium waste, scrap and...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6461,846912,"Typewriters, automatic (excluding word-process...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6462,847971,"Passenger boarding bridges, of a kind used in ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6463,852731,"Radio-broadcast receivers, for mains operation...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6464,851921,Record players without loudspeaker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
Iran_Turkey_All_filledNAs

,Code,Product label,2003_Iran_Exports,2004_Iran_Exports,2005_Iran_Exports,2006_Iran_Exports,2007_Iran_Exports,2008_Iran_Exports,2009_Iran_Exports,2010_Iran_Exports,...,2013_Potential,2014_Potential,2015_Potential,2016_Potential,2017_Potential,2018_Potential,2019_Potential,2020_Potential,2021_Potential,2022_Potential
0,270900,Petroleum oils and oils obtained from bitumino...,26124000.0,34289000.0,48286000.0,50223930.0,60382065.0,81415379.0,49408527.0,72350088.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,271000,Petroleum oils and oils obtained from bitumino...,0.0,0.0,0.0,0.0,7864367.0,7510337.0,6279883.0,9682267.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,271112,"Propane, liquefied",212939.0,209251.0,262450.0,655989.0,972457.0,1150711.0,968805.0,1422892.0,...,89106.0,76278.0,39799.0,37005.0,62486.0,63672.0,0.0,0.0,107078.0,122882.0
3,310210,"Urea, whether or not in aqueous solution (excl...",13302.0,3928.0,0.0,0.0,0.0,36467.0,111424.0,431656.0,...,634390.0,607704.0,461484.0,507696.0,679049.0,593052.0,711715.0,587862.0,1136453.0,1695848.0
4,290511,"Methanol ""methyl alcohol""",846.0,27531.0,193184.0,163880.0,632725.0,903917.0,649704.0,1048625.0,...,217586.0,246069.0,172249.0,120581.0,205228.0,242231.0,142298.0,118479.0,235246.0,236116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,841121,Turbopropellers of a power <= 1.100 kW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6418,846920,"Typewriters, electric (excluding automatic typ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6419,851910,Coin-operated or disc-operated record-players,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6420,851931,"Turntables ""record-decks"", with automatic reco...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6421,851940,Transcribing machines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0