In [4]:
import pandas as pd
import numpy as np
import os

29309990 has changed to 29309090

Check it all the times

In [5]:
Data = pd.read_excel(f'C:/TradeGroup/Reports/Tamin_Kalaee_Mahramane_DeletedIDs_6mahe1403.xlsx')
Data_Details = pd.read_excel(f'C:/TradeGroup/Data/Dashboard/HSs_complete_Final31.xlsx')


Data_Details

,HS6,HS6_E,HS6_F,HS4,HS2,HS5,HS4_E,HS4_F,Harvard_F,HS2_F,Harvard_E,HS2_E
0,10110,Live horses/asses/mules/hinnies: pure-bred bre...,اسب زنده / الاغ / قاطر / مرغ مرغ زنده: حیوانات...,101.0,1.0,1011.0,Horses,اسب‌ها,کشاورزی,حیوان زنده,Agriculture,Live animals
1,10111,"Horses, live pure-bred breeding",اسب، پرورش نژاد خالص زنده,101.0,1.0,1011.0,Horses,اسب‌ها,کشاورزی,حیوان زنده,Agriculture,Live animals
2,10119,"Horses, live except pure-bred breeding",اسب‌ها به جز نژاد خالص زنده,101.0,1.0,1011.0,Horses,اسب‌ها,کشاورزی,حیوان زنده,Agriculture,Live animals
3,10120,"Asses, mules and hinnies, live",الاغ‌ها، قاطرها و حشرات، زنده,101.0,1.0,1012.0,Horses,اسب‌ها,کشاورزی,حیوان زنده,Agriculture,Live animals
4,10121,Horses : Pure-bred breeding animals,اسب: حیوانات اصیل مولد,101.0,1.0,1012.0,Horses,اسب‌ها,کشاورزی,حیوان زنده,Agriculture,Live animals
...,...,...,...,...,...,...,...,...,...,...,...,...
6795,999602,Advance freight for export goods,پیش کرایه حمل کالاهای صادراتی,9996.0,99.0,99960.0,Advance freight for export goods,پیش کرایه حمل کالاهای صادراتی,سایر,سایر,Other,Other
6796,999700,Registration of service,ثبت خدمت,9997.0,99.0,99970.0,Registration of service,ثبت خدمت,سایر,سایر,Other,Other
6797,999701,Registration of service of other foreign excha...,ثبت خدمت سایر مصارف ارزی خدماتی (غیربازرگانی) ...,9997.0,99.0,99970.0,Registration of service,ثبت خدمت,سایر,سایر,Other,Other
6798,999999,"Commodities not specified, according to kind",کالاها بر اساس نوع مشخص نشده است,9999.0,99.0,99999.0,Commodities not specified according to kind,کالاها بر اساس نوع مشخص نشده‌اند,سایر,سایر,Other,Other
6799,999999,"Commodities not specified, according to kind",کالاها بر اساس نوع مشخص نشده است,9999.0,99.0,99999.0,Commodities not specified according to kind,کالاها بر اساس نوع مشخص نشده‌اند,سایر,سایر,Other,Other

In [3]:
Data['HS6'] = Data['HS8']//100
Detailed_Data = Data.merge(Data_Details,on='HS6',how='left')

Detailed_Data.to_excel(f'C:/TradeGroup/Data/Indices/Tamin_Arz_Mahramaneh_Dashboard_6mahe1403.xlsx',index=False)